### ISSUE TITLE
WithFrom and WithUntil options - Do they really work?

### ISSUE THREAD

**Issue by postacik** [emitter-io/go#19]
I tested from and until options with my C# library but could not get them working.

Can you please confirm that these options actually work?

PS: There is a bug in WithUntil option in the go source code:

```
// WithUntil request messages until a point in time.
func WithUntil(until time.Time) Option {
	return option("from=" + strconv.FormatInt(getUTCTimestamp(until), 10))
}
```
`"from="` must be `"until="`

**Comment by postacik** [comment]
The following is a sample of the formatted channel data used for subscribing:

`jCbClCwMZg7eI2Z7Q0Amg4WVIJ9rspQj/test/device1/?last=10000&from=1557830446&until=1557830456`

**Comment by postacik** [comment]
I was testing on my local emitter server. (emitter-windows-amd64.exe)

I repeated the same test on the emitter cloud and it worked as expected.

Can you tell me why this may happen?

**Comment by postacik** [comment]
I repeated the test with emitter-linux-amd64 on Ubuntu and it did not work as on Windows. :(

**Comment by postacik** [comment]
Last note: I am using the binaries I built from the latest master.

**Comment by Florimond** [comment]
If Last works as expected then the storage is correctly configured.
Then I would say that it's a problem of UTC vs local time?

**Comment by postacik** [comment]
The same code is tested on cloud, local Windows and local Ubuntu.

Only the cloud works as expected.

I subscribe to a channel using last = 1000, from = now - 10 seconds and until = now.

On the cloud, no messages arrive after 10 seconds.

On the others, the non expired messages keep coming even after 10 seconds.

Can you try testing it on a local instance of emitter?

**Comment by postacik** [comment]
`If Last works as expected then the storage is correctly configured.`

I specified `"provider": "ssd"` in local emitter configuration and now it works.

Can you please put this somewhere in `readme`?

**Comment by kelindar** [comment]
This https://github.com/emitter-io/emitter/pull/239 should fix range queries for the memory storage.
