### ISSUE TITLE
Subcribe and Publish methods does not send any errors

### ISSUE THREAD

**Issue by paulogr** [emitter-io/go#2]
I'm trying your mqtt server and using this client to do my tests. And just realize that I don't get any errors if I set my key or channel wrong.

```
func (h *Hub) Subscribe() {
	sToken := h.c.Subscribe("wrong key", "wrong channel")
	if sToken.Wait() && sToken.Error() != nil {
		log.Fatalln("Error on Hub.Subscribe(): " + sToken.Error().Error())
	}
}
```

This issue put me in the dark for a hour until I realize that I'm using a wrong key.

Thank you.

**Comment by mshafiee** [comment]
There is no error handling in:

https://github.com/emitter-io/emitter/blob/5878cce20b9a30facbd1a196e801a668fccd1bec/broker/conn.go#L172

So the client don't be informed if  the security key is invalid.
