### ISSUE TITLE
Message handlers not called

### ISSUE THREAD

**Issue by millerlogic** [emitter-io/go#23]
Hi, if you don't set the default OnMessage, the specific message handlers to Subscribe are not called. I just wasted more time on this than I'd like to admit.
I see the [fix is here](https://github.com/emitter-io/go/commit/0bd5959ef4b933acf64ad27489fd616dcf4825df), so it would be nice to get a new version tag.

**Comment by Florimond** [comment]
Hello @millerlogic,

here is the new version tag : https://github.com/emitter-io/go/tree/v2.0.5

Thank you for your feedback !
