### ISSUE TITLE
I want to join developers

### ISSUE THREAD

**Issue by uppercaveman** [emitter-io/go#29]
I want to join developers

I want to increase ： SetCleanSession and QoS=2 configuration

**Comment by kelindar** [comment]
Hey, contributions are welcome! For session there needs to be a cluster-level session management implemented, which we don't have right now in the broker. Emitter is not a MQTT broker per say, since it's clustered and AP (in CAP terms). So we need to think how to keep the session state between connections.

**Comment by uppercaveman** [comment]
I know, let me think about the cluster-level session.

I now have another problem. QoS=1 or QoS=2. I modified the client code and added QoS = 2, but it did not achieve the expected effect. QoS = 1 is the same.

For example: when the client is disconnected, the previous messages cannot be received after restarting, and only the latest ones can be received.

Is it because I have a misunderstanding of the MQTT protocol?

QoS =1 received at most once
QoS = 2 Only received once

**Comment by uppercaveman** [comment]
I know the source of the problem。

emitter code ：

func (c *Conn) Send(m *message.Message) (err error) {
	defer c.MeasureElapsed("send.pub", time.Now())
	packet := mqtt.Publish{
		**Header:  mqtt.Header{QOS: 0},**
		Topic:   m.Channel, // The channel for this message.
		Payload: m.Payload, // The payload for this message.
	}

	_, err = packet.EncodeTo(c.socket)
	return
}

No matter what you configure QoS when publishing, the QoS received when subscribing will output 0

It makes me sad。

**Comment by uppercaveman** [comment]
I see that QoS may not matter because there is no cluster-level session management

**Comment by uppercaveman** [comment]
I'm going to read the emitter code carefully and think about it
