### ISSUE TITLE
multiple-value uuid.NewV1() in single-value context

### ISSUE THREAD

**Issue by MadDataScience** [emitter-io/go#3]
When I try to `go get github.com/emitter-io/go` I get:
```
# github.com/emitter-io/go
../../go/src/github.com/emitter-io/go/options.go:35:35: multiple-value uuid.NewV1() in single-value context
```
https://github.com/emitter-io/go/blob/f6f9eac6def41f295a41807c62b4d065189910f1/options.go#L35

**Comment by Kelindar** [comment]
This issue is now fixed and all of the dependencies are now in the `vendor` folder so you should not have to manually install any dependencies anymore.
