### ISSUE TITLE
assignment mismatch: 2 variables but 1 values

### ISSUE THREAD

**Issue by amirkheirabadi** [emitter-io/go#4]
When I try to run the sample on the first line:
```
o := emitter.NewClientOptions()
```

 I getting this error: 
```
vendor/github.com/emitter-io/go/options.go:33:10: assignment mismatch: 2 variables but 1 values
```
How can I solve this?

**Comment by Kelindar** [comment]
I suspect your build doesn't compile in the right `uuid` library version. Make sure you use the one vendored which should work fine. Or run ` go get -u github.com/satori/go.uuid`.

**Comment by amirkheirabadi** [comment]
Thx, the problem was solved. I used dep for install dependency and uuid that installed by dep wasn't the last version.

**Comment by Synaxis** [comment]
thanks..
