### ISSUE TITLE
please update vender "github.com/satori/go.uuid" to v1.2.0

### ISSUE THREAD

**Issue by vvhh2003** [emitter-io/go#6]
there are error in at "emitter-io/go/options.go:33:10: assignment mismatch: 2 variables but 1 values"

**Comment by Kelindar** [comment]
Make sure you update the package, it is likely that you have an older version of uuid. `go get -u github.com/emitter-io/go`

**Comment by vvhh2002** [comment]
It is precisely that you used an old version of  "github.com/satori/go.uuid" at  "emitter-io/go/options.go:33:10" . If you use dep package management, you can't compile it. I suggest updating to the latest version.
thanks.

**Comment by vvarp** [comment]
I second that - when using `github.com/emitter-io/go` with dep, I need to make sure that my `Gopkg.toml` is pointing to an older version of `github.com/satori/go.uuid`

**Comment by Kelindar** [comment]
Not sure what you mean, we are using the latest version of `github.com/satori/go.uuid`. Feel free to submit a PR to clarify.

**Comment by Christopotamus** [comment]
From a completely fresh install, running `go get -u github.com/emitter-io/go` I get 

``` 
# github.com/emitter-io/go
../../../go/src/github.com/emitter-io/go/options.go:33:18: multiple-value uuid.NewV1() in single-value context
```
This was on a fresh install of go and is the first time I've tried to install emitter-io/go.

**Comment by hankchan** [comment]
@Kelindar I have got the same problem with Christopotamus.

**Comment by ivanjaros** [comment]
It is not fixed, that's why https://github.com/emitter-io/go/blob/master/options.go#L33
Also, don't use satori, basically it is deprecated. Use google or gofrs(see https://github.com/satori/go.uuid/issues/84).
