### ISSUE TITLE
github.com/emitter-io/go/options.go:33:10: assignment mismatch: 2 variables but 1 values

### ISSUE THREAD

**Issue by richterk** [emitter-io/go#7]
So, the NewV1 function signature has changed.  It no longer returns an id and an error.  It just needs to be changed to accept that NewV1 is no longer faulty, so it can't return an error.   I'm happy to submit a PR if that's okay. I keep modifying this locally, but every time I update a dependency and run dep ensure, my change gets blown away, and my app won't compile anymore.  I'd much rather this just be updated. :)

**Comment by richterk** [comment]
Also, you should probably note in the README that the example does not keep a live connection.  It just executes and exits, so it will never receive any events.  It just publishes something and then exits.

**Comment by TaibiaoGuo** [comment]
I found that problem too and open a pull request in November. :-)

**Comment by richterk** [comment]
This is fixed with my PR:

https://github.com/emitter-io/go/pull/8
